version: 2
updates:

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"

  # This is disabled so as to showcase the dependabot vulnerability PRs feature over the generic vesion updates this provides
  # Set update schedule for Maven
  # - package-ecosystem: "maven"
  #   directory: "/"
  #   schedule:
  #     # Check for updates to GitHub Actions every day
  #     interval: "daily"

  # Set update schedule for Terraform
  - package-ecosystem: "terraform"
    directory: "/.demo/terraform"
    schedule:
      # Check for updates to Terraform every month
      interval: "monthly"
