name: Code scanning 
on:
  push:
    branches:
      - main
      - '!dependabot/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  codeql:
    uses: expert-services/reusable-workflows/.github/workflows/codeql.yml@main
    with:
      buildCmd: mvn compile -B
      java-version: 11
      java-distribution: microsoft
