name: Code scanning
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  codeql:
    uses: expert-services/reusable-workflows/.github/workflows/codeql.yml@main
    with:
      queries: ${{ github.event.repository.custom_properties.codeql-query-suite }}
      languages: ${{ github.event.repository.custom_properties.codeql-languages }}
      buildCmd: mvn compile -B
      java-version: 11
      distribution: microsoft
