name: Dependency Review

on:
  pull_request:
  workflow_dispatch:
jobs:
  dependency_review:
    uses: oodles-noodles/reusable-workflows/.github/workflows/dependency_review.yml@main
    with:
      ecosystem: maven
      java-version: 11
      java-distribution: microsoft
