name: Dependency Review

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  maven_dependency_analysis:
    name: Maven
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: 11
            java-distribution: microsoft
            directory: someDir
    permissions:
      contents: write
      statuses: write
    uses: expert-services/reusable-workflows/.github/workflows/dependency_review.yml@testing
    with:
      java-version: ${{ matrix.java-version }} 
      java-distribution: ${{ matrix.java-distribution}} 
      directory: ${{ matrix.directory }}
